services:
  db:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432  #host_port:container_port
    volumes:
      - pgdata:/var/lib/postgresql/data   #hostPath:container_path

  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build: 
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build: 
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=${FLASK_APP_URL}
    depends_on:
      - flaskapp

volumes:
  pgdata: {}